const { Sneakers } = require('../models');

const sneakersData = [
  {
    sneaker_name: 'Jordan 1 Dior',
    price: 25000.00,
    stock: 3,
    img: '/images/jordan1dior.png',
    brand_id: 1,
    type_id: 1,
  },
  {
    sneaker_name: 'Jordan 1 Off-White',
    price: 10000.00,
    stock: 7,
    img: '/images/jordan1offwhite.png',
    brand_id: 1,
    type_id: 1,
  },
  {
    sneaker_name: 'Jordan 4 Cement',
    price: 1200.00,
    stock: 12,
    img: '/images/jordan4cement.png',
    brand_id: 1,
    type_id: 1,
  },
  {
    sneaker_name: 'New Balance 550 UNC White University Blue ',
    price: 160.00,
    stock: 25,
    img: '/images/nb550NC.png',
    brand_id: 4,
    type_id: 3,
  },
  {
    sneaker_name: 'Nike Patta x Air Max 1',
    price: 345.00,
    stock: 20,
    img: '/images/Nikeam1patta.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Nike DQM x Air Max 90 Bacon',
    price: 215.00,
    stock: 18,
    img: '/images/Nikeam90bacon.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Nike Air Max 90 Infrared',
    price: 222.00,
    stock: 16,
    img: '/images/Nikeam90infared.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Nike Dunk High LX Toasty',
    price: 285.00,
    stock: 13,
    img: '/images/NikeDunkpadded.png',
    brand_id: 2,
    type_id: 1,
  },
  {
    sneaker_name: 'Nike SB Dunk Low Paris',
    price: 150000.00,
    stock: 1,
    img: '/images/nikeparisdunk.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: "Nike SB Dunk Low Ben & Jerry's Chunky Dunky",
    price: 1420.00,
    stock: 3,
    img: '/images/chunkydunky.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Adidas Yeezy Boost 350 V2 MX Oat',
    price: 240.00,
    stock: 10,
    img: '/images/yzymx.png',
    brand_id: 3,
    type_id: 3,
  },/////////////////
  {
    sneaker_name: 'Adidas disney SW',
    price: 240.00,
    stock: 10,
    img: '/images/adidasdisneySW.png',
    brand_id: 3,
    type_id: 3,
  },
  {
    sneaker_name: 'Air Footscape Woven Chuka Knit',
    price: 240.00,
    stock: 15,
    img: '/images/AirFootscapeWovenChukaKnit.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Air Force 1 Low Only Once',
    price: 240.00,
    stock: 12,
    img: '/images/AirForce1LowOnlyOnce.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'asics koi',
    price: 240.00,
    stock: 22,
    img: '/images/asicskoi.png',
    brand_id: 5,
    type_id: 2,
  },
  {
    sneaker_name: 'asics 24k',
    price: 240.00,
    stock: 11,
    img: '/images/asics24k.png',
    brand_id: 5,
    type_id: 2,
  },
  {
    sneaker_name: 'asics orange koi',
    price: 240.00,
    stock: 14,
    img: '/images/asicsorangekoi.png',
    brand_id: 5,
    type_id: 2,
  },
  {
    sneaker_name: 'bodega better days',
    price: 240.00,
    stock: 9,
    img: '/images/bodegabetterdays.png',
    brand_id: 4,
    type_id: 3,
  },
  {
    sneaker_name: 'bodega no days off',
    price: 240.00,
    stock: 4,
    img: '/images/bodeganodaysoff.png',
    brand_id: 4,
    type_id: 3,
  },
  {
    sneaker_name: 'bodega no bad days',
    price: 240.00,
    stock: 2,
    img: '/images/bodeganobaddays.png',
    brand_id: 4,
    type_id: 3,
  },
  {
    sneaker_name: 'jordan 4 kaws',
    price: 240.00,
    stock: 3,
    img: '/images/jordan4kaws.png',
    brand_id: 1,
    type_id: 1,
  },
  {
    sneaker_name: 'kith 4d aspen',
    price: 240.00,
    stock: 10,
    img: '/images/kith4daspen.png',
    brand_id: 3,
    type_id: 2,
  },
  {
    sneaker_name: 'Kith Ultra boost aspen',
    price: 240.00,
    stock: 17,
    img: '/images/KithUltraboostaspen.png',
    brand_id: 3,
    type_id: 2,
  },
  {
    sneaker_name: 'Nike sean w other spoon',
    price: 240.00,
    stock: 6,
    img: '/images/Nikeseanwotherspoon.png',
    brand_id: 2,
    type_id: 3,
  },
  {
    sneaker_name: 'Salmon toe asics gel 5',
    price: 240.00,
    stock: 45,
    img: '/images/Salmontoeasicsgel5.png',
    brand_id: 5,
    type_id: 2,
  },
  {
    sneaker_name: 'south beach LB 8',
    price: 240.00,
    stock: 1,
    img: '/images/southbeachLB8.png',
    brand_id: 2,
    type_id: 1,
  },
  
  




];

const seedSneakers = () => Sneakers.bulkCreate(sneakersData);

module.exports = seedSneakers;
